"""locations removed

Revision ID: b7e1220b7cd2
Revises: cbe08411c11b
Create Date: 2019-03-21 20:57:05.018509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e1220b7cd2'
down_revision = 'cbe08411c11b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
